# Configuração de Base de Dados
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/rms_security?createDatabase
IfNotExist=true&serverTimezone=UTC
spring.datasource.username=rms
spring.datasource.password=2diSenai
# Show SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false