spring.application.name=Security
# Habilitar o H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações de Conexão (exemplo em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=rms
spring.datasource.password=2diSenai

spring.application.name=SecurityJwt
# Define cores no terminal
spring.output.ansi.enabled=always
spring.profiles.active=test
#spring.profiles.active=prod

app.jwt.secret=rzbolcnV4R624B3ujHFqEX1MHXBxpSzH5WDHsMsHBMBkIsQ46ufnWo42YsE0HTw91i4BM96q3ePTaEHZSXpfWw==